# Generated by Django 3.0.9 on 2020-08-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=155, verbose_name='Категория')),
            ],
            options={
                'verbose_name_plural': 'Категории',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.TextField(verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('url_to_record', models.CharField(max_length=155, verbose_name='Ссылка на ориг. запись')),
                ('url_to_image', models.CharField(max_length=155, verbose_name='Ссылка на фото')),
                ('date', models.CharField(max_length=155, verbose_name='Дата')),
            ],
            options={
                'verbose_name_plural': 'Новости',
                'ordering': ['id'],
            },
        ),
    ]
