# Generated by Django 3.0.9 on 2020-08-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200804_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=255, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.CharField(max_length=255, verbose_name='Ссылка на фото'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.CharField(max_length=255, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='news',
            name='url_to_image',
            field=models.CharField(max_length=255, verbose_name='Ссылка на фото'),
        ),
        migrations.AlterField(
            model_name='news',
            name='url_to_record',
            field=models.CharField(max_length=255, verbose_name='Ссылка на ориг. запись'),
        ),
    ]
