# Generated by Django 3.0.9 on 2020-08-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200805_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='url_to_image',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ссылка на фото'),
        ),
    ]
